/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppHeader: typeof import('./src/components/AppHeader.vue')['default']
    BashMessage: typeof import('./src/components/message/BashMessage.vue')['default']
    BashTool: typeof import('./src/components/tool-use/BashTool.vue')['default']
    Button: typeof import('primevue/button')['default']
    ChatLayout: typeof import('./src/components/ChatLayout.vue')['default']
    ChatMessage: typeof import('./src/components/ChatMessage.vue')['default']
    ClaudeUserMessage: typeof import('./src/components/message/ClaudeUserMessage.vue')['default']
    Dialog: typeof import('primevue/dialog')['default']
    DirectoryPicker: typeof import('./src/components/DirectoryPicker.vue')['default']
    EditMessage: typeof import('./src/components/message/EditMessage.vue')['default']
    ExitPlanModeMessage: typeof import('./src/components/message/ExitPlanModeMessage.vue')['default']
    ExitPlanModeOptions: typeof import('./src/components/ExitPlanModeOptions.vue')['default']
    FallbackMessage: typeof import('./src/components/message/FallbackMessage.vue')['default']
    FileEditTool: typeof import('./src/components/tool-use/FileEditTool.vue')['default']
    FileWriteTool: typeof import('./src/components/tool-use/FileWriteTool.vue')['default']
    InputText: typeof import('primevue/inputtext')['default']
    MarkdownRenderer: typeof import('./src/components/message/MarkdownRenderer.vue')['default']
    MessageInput: typeof import('./src/components/MessageInput.vue')['default']
    MessageList: typeof import('./src/components/MessageList.vue')['default']
    MultiEditMessage: typeof import('./src/components/message/MultiEditMessage.vue')['default']
    MultiEditTool: typeof import('./src/components/tool-use/MultiEditTool.vue')['default']
    PermissionOptions: typeof import('./src/components/PermissionOptions.vue')['default']
    ProgressSpinner: typeof import('primevue/progressspinner')['default']
    ReadMessage: typeof import('./src/components/message/ReadMessage.vue')['default']
    ResultMessage: typeof import('./src/components/message/ResultMessage.vue')['default']
    Select: typeof import('primevue/select')['default']
    SlashCommandList: typeof import('./src/components/slash-commands/SlashCommandList.vue')['default']
    SystemMessage: typeof import('./src/components/message/SystemMessage.vue')['default']
    TextMessage: typeof import('./src/components/message/TextMessage.vue')['default']
    TodoWriteMessage: typeof import('./src/components/message/TodoWriteMessage.vue')['default']
    UnknownToolUseMessage: typeof import('./src/components/message/UnknownToolUseMessage.vue')['default']
    WelcomeScreen: typeof import('./src/components/WelcomeScreen.vue')['default']
    WriteMessage: typeof import('./src/components/message/WriteMessage.vue')['default']
  }
  export interface GlobalDirectives {
    Tooltip: typeof import('primevue/tooltip')['default']
  }
}
