/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppHeader: typeof import('./src/components/AppHeader.vue')['default']
    ChatLayout: typeof import('./src/components/ChatLayout.vue')['default']
    ChatMessage: typeof import('./src/components/ChatMessage.vue')['default']
    MessageInput: typeof import('./src/components/MessageInput.vue')['default']
    MessageList: typeof import('./src/components/MessageList.vue')['default']
  }
}
