/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppHeader: typeof import('./src/components/AppHeader.vue')['default']
    BashMessage: typeof import('./src/components/message/BashMessage.vue')['default']
    BashRenderer: typeof import('./src/components/message/BashRenderer.vue')['default']
    BashTool: typeof import('./src/components/tool-use/BashTool.vue')['default']
    Button: typeof import('primevue/button')['default']
    ChatLayout: typeof import('./src/components/ChatLayout.vue')['default']
    ChatMessage: typeof import('./src/components/ChatMessage.vue')['default']
    Dialog: typeof import('primevue/dialog')['default']
    EditMessage: typeof import('./src/components/message/EditMessage.vue')['default']
    EditRenderer: typeof import('./src/components/message/EditRenderer.vue')['default']
    FallbackMessage: typeof import('./src/components/message/FallbackMessage.vue')['default']
    FallbackRenderer: typeof import('./src/components/message/FallbackRenderer.vue')['default']
    FileEditTool: typeof import('./src/components/tool-use/FileEditTool.vue')['default']
    FileWriteTool: typeof import('./src/components/tool-use/FileWriteTool.vue')['default']
    MarkdownRender: typeof import('./src/components/renderers/MarkdownRender.vue')['default']
    MarkdownRenderer: typeof import('./src/components/message/MarkdownRenderer.vue')['default']
    MessageInput: typeof import('./src/components/MessageInput.vue')['default']
    MessageList: typeof import('./src/components/MessageList.vue')['default']
    MultiEditMessage: typeof import('./src/components/message/MultiEditMessage.vue')['default']
    MultiEditRenderer: typeof import('./src/components/message/MultiEditRenderer.vue')['default']
    ProgressSpinner: typeof import('primevue/progressspinner')['default']
    ReadMessage: typeof import('./src/components/message/ReadMessage.vue')['default']
    ReadRenderer: typeof import('./src/components/message/ReadRenderer.vue')['default']
    ResultMessage: typeof import('./src/components/message/ResultMessage.vue')['default']
    ResultRenderer: typeof import('./src/components/message/ResultRenderer.vue')['default']
    SystemMessage: typeof import('./src/components/message/SystemMessage.vue')['default']
    SystemRenderer: typeof import('./src/components/message/SystemRenderer.vue')['default']
    Tag: typeof import('primevue/tag')['default']
    TextMessage: typeof import('./src/components/message/TextMessage.vue')['default']
    TextRenderer: typeof import('./src/components/message/TextRenderer.vue')['default']
    Toast: typeof import('primevue/toast')['default']
    TodoWriteMessage: typeof import('./src/components/message/TodoWriteMessage.vue')['default']
    TodoWriteRenderer: typeof import('./src/components/message/TodoWriteRenderer.vue')['default']
    ToolPermissionDialog: typeof import('./src/components/ToolPermissionDialog.vue')['default']
    UserMessageRenderer: typeof import('./src/components/renderers/UserMessageRenderer.vue')['default']
    Write: typeof import('./src/components/permission-renders/Write.vue')['default']
    WriteInput: typeof import('./src/components/permission/WriteInput.vue')['default']
    WriteMessage: typeof import('./src/components/message/WriteMessage.vue')['default']
    WriteRenderer: typeof import('./src/components/message/WriteRenderer.vue')['default']
  }
}
